// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Aukora
//
// CONSOLE — a center-pane organ (R34, issue #23). NOT donor code: this file and app/console/* are ours,
// carried from the apps/console evidence (panels.js + DEMO_FIXTURE + styles). It mounts the ten tested
// read-only operator panels inside the donor shell WITHOUT touching donor chrome: the panels render in a
// ShadowRoot so the evidence stylesheet cannot clash with the donor style.css, and the shadow host maps
// the evidence design vars onto the donor tokens. Read-only; signs, applies, and arms nothing.

const ORDER = ['authority', 'memory', 'lineage', 'recursion', 'council', 'providers', 'budget', 'convex', 'g1', 'forgetting'];

// The evidence vars → donor token mapping (set on the shadow host; custom properties inherit into shadow).
const VAR_MAP = {
  '--bg': 'transparent',
  '--panel': 'var(--glass)',
  '--panel-2': 'rgba(255, 255, 255, 0.06)',
  '--line': 'var(--glass-border)',
  '--line-strong': 'rgba(255, 255, 255, 0.16)',
  '--ink': 'var(--text)',
  '--ink-soft': 'var(--dim)',
  '--ink-faint': 'var(--faint)',
  '--accent': 'rgb(var(--hue-c))',
  '--ok': 'rgb(var(--hue-l))',
  '--warn': '#e2b04a',
  '--info': 'rgb(var(--hue-r))',
  '--ok-bg': 'rgba(var(--hue-l), 0.12)',
  '--warn-bg': 'rgba(226, 176, 74, 0.14)',
  '--info-bg': 'rgba(var(--hue-r), 0.12)',
  '--shadow': 'none',
  '--radius': '14px',
  '--mono': 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
  '--sans': 'ui-sans-serif, system-ui, -apple-system, sans-serif',
};

function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error('failed to load ' + src));
    document.head.append(s);
  });
}

export async function mountConsole(root) {
  const host = document.createElement('div');
  host.style.position = 'absolute';
  host.style.inset = '0';
  host.style.overflowY = 'auto';
  for (const [k, v] of Object.entries(VAR_MAP)) host.style.setProperty(k, v);
  root.append(host);

  const shadow = host.attachShadow({ mode: 'open' });
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = '/app/console/console.css';
  shadow.append(link);

  const wrap = document.createElement('div');
  wrap.style.padding = '8px 22px 26px';
  shadow.append(wrap);

  try {
    // The evidence files define plain globals (AUKORA_CONSOLE_FIXTURE, AukoraPanels) — load once.
    if (!window.AukoraPanels || !window.AUKORA_CONSOLE_FIXTURE) {
      await loadScript('/app/console/fixture.js');
      await loadScript('/app/console/panels.js');
    }
    const F = window.AUKORA_CONSOLE_FIXTURE;
    const P = window.AukoraPanels;
    const note = document.createElement('p');
    note.textContent = 'Read-only operator panels · ' + (F.label || 'DEMO_FIXTURE') + ' — every value generated by the real organism offline.';
    note.style.cssText = 'font-size:12.5px;color:var(--ink-faint);margin:6px 0 12px';
    wrap.append(note);
    const grid = document.createElement('div');
    grid.style.cssText = 'display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px';
    for (const id of ORDER) grid.append(P.render[id](F));
    wrap.append(grid);
  } catch (err) {
    // Loud refusal state — never a silent blank pane.
    const fail = document.createElement('p');
    fail.textContent = 'Console evidence failed to load: ' + (err && err.message ? err.message : err);
    fail.style.cssText = 'color:#e2b04a;font-size:13px;padding:12px';
    wrap.append(fail);
  }
}
